/**
 * data.js — Données des produits et utilisateurs statiques
 * FemSport — Boutique Sport Femme
 */

/* =============================================
   PRODUITS
   ============================================= */
const PRODUCTS = [
  /* ---------- LEGGINGS ---------- */
  {
    id: 1,
    name: "Legging Nike",
    category: "leggings",
    price: 49.99,
    oldPrice: null,
    description: "Un legging Nike classique alliant confort et performance pour vos entraînements quotidiens.",
    image: "images/produits/legging_nike.jpg",
    badge: null,
    colors: ["#1a1a2e", "#E63946", "#4A90D9"],
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.9,
    reviews: 248,
    stock: 2,
    featured: true,
    comments: [
      { user: "Inès M.", date: "10 Jan. 2026", rating: 5, text: "Incroyable ! Il ne bouge pas pendant mes séances de cardio, et la matière est très douce." },
      { user: "Sonia T.", date: "02 Jan. 2026", rating: 4, text: "Excellent maintien, j'adore la coupe. Livraison rapide." }
    ]
  },
  {
    id: 2,
    name: "Legging Oysho",
    category: "leggings",
    price: 44.99,
    oldPrice: null,
    description: "Un legging technique Oysho offrant une grande liberté de mouvement et un design épuré, idéal pour le yoga et le fitness.",
    image: "images/produits/legging_oysho.jpg",
    badge: null,
    colors: ["#1a1a2e", "#8A9A5B", "#F5F0EC"],
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.7,
    reviews: 89,
    featured: true,
    comments: [
      { user: "Lila R.", date: "15 Jan. 2026", rating: 5, text: "La coupe est parfaite et le maintien est au rendez-vous. Très satisfaite de cet achat." },
      { user: "Amel B.", date: "08 Jan. 2026", rating: 4, text: "Tissu très agréable et résistant. Je recommande." }
    ]
  },
  {
    id: 3,
    name: "Jogging Nike Sportswear",
    category: "leggings",
    price: 59.99,
    oldPrice: null,
    description: "Un bas de jogging Nike ultra-confortable en tissu Fleece, parfait pour l'entraînement ou un look décontracté au quotidien.",
    image: "images/produits/jogging_nike.jpg",
    badge: null,
    colors: ["#2D2D2D", "#FF6B6B", "#4A90D9"],
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.6,
    reviews: 156,
    featured: false
  },

  /* ---------- BRASSIÈRES & TOPS ---------- */
  {
    id: 4,
    name: "Jogging Adidas Tiro",
    category: "leggings",
    price: 64.99,
    oldPrice: null,
    description: "Le pantalon de survêtement iconique Adidas Tiro, alliant style classique et technologie respirante pour vos activités sportives.",
    image: "images/produits/jogging_adidas.jpg",
    badge: null,
    colors: ["#E63946", "#FF9F1C", "#F5F0EC"],
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.8,
    reviews: 312,
    stock: 4,
    featured: true,
    comments: [
      { user: "Célia H.", date: "12 Déc. 2025", rating: 5, text: "Enfin une brassière qui tient vraiment pour la boxe ! Je recommande à 100%." }
    ]
  },
  {
    id: 5,
    name: "Tank Top Adidas",
    category: "brassieres",
    price: 34.99,
    oldPrice: null,
    description: "Un débardeur Adidas léger et respirant, conçu pour offrir une liberté de mouvement totale pendant vos entraînements.",
    image: "images/produits/tanktop_adidas.jpg",
    badge: null,
    colors: ["#D4A5A5", "#F0E6D3", "#2D2D2D"],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.5,
    reviews: 67,
    featured: false
  },
  {
    id: 6,
    name: "Sweat Nike",
    category: "brassieres",
    price: 69.99,
    oldPrice: null,
    description: "Le sweat Nike classique, alliant style streetwear et confort thermique exceptionnel pour l'après-sport.",
    image: "images/produits/sweat_nike.jpg",
    badge: "Bestseller",
    colors: ["#1a1a2e", "#6B7A8D"],
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.7,
    reviews: 201,
    featured: true
  },

  /* ---------- CHAUSSURES ---------- */
  {
    id: 7,
    name: "Baskets Nike Air Monarch",
    category: "chaussures",
    price: 119.99,
    oldPrice: 149.99,
    description: "Le confort légendaire de la Nike Air Monarch, idéale pour l'entraînement intensif ou un look décontracté au quotidien.",
    image: "images/produits/Baskets_Air_Monarch_blanches.jpg",
    badge: "Promo",
    colors: ["#F5F0EC", "#E63946", "#4A90D9"],
    sizes: ["36", "37", "38", "39", "40", "41"],
    rating: 4.9,
    reviews: 445,
    stock: 1,
    featured: true
  },
  {
    id: 8,
    name: "Hijab Sport",
    category: "accessoires",
    price: 29.99,
    oldPrice: null,
    description: "Un hijab de sport léger et respirant, conçu pour un maintien sûr et un confort optimal pendant l'exercice. Idéal pour toutes les activités physiques.",
    image: "images/produits/Womens_Ladies_Hijab.jpg",
    badge: "Nouveau",
    colors: ["#2D2D2D", "#FFFFFF", "#A37B92"],
    sizes: ["Unique"],
    rating: 4.9,
    reviews: 55,
    featured: false
  },
  {
    id: 9,
    name: "Baskets Nike P-6000",
    category: "chaussures",
    price: 109.99,
    oldPrice: null,
    description: "Un look running rétro inspiré de la Pegasus 2006. La Nike P-6000 allie mesh respirant et renforts horizontaux pour un confort durable et un style urbain affirmé.",
    image: "images/produits/Baskets_Nike_argentees.jpg",
    badge: null,
    colors: ["#FFFFFF", "#A0A0AE", "#2D2D2D"],
    sizes: ["36", "37", "38", "39", "40"],
    rating: 4.4,
    reviews: 92,
    featured: false
  },

  /* ---------- ACCESSOIRES ---------- */
  {
    id: 10,
    name: "Tunique Adidas Manches Longues",
    category: "brassieres",
    price: 54.99,
    oldPrice: null,
    description: "Une tunique Adidas à manches longues alliant style et performance. Son tissu respirant et sa coupe fluide vous offrent un confort optimal pendant vos entraînements.",
    image: "images/produits/Tunique_Adidas_Manches_Longues.jpg",
    badge: null,
    colors: ["#2D2D2D", "#FFFFFF", "#6B7A8D"],
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.8,
    reviews: 124,
    featured: true
  },
  {
    id: 11,
    name: "Sweat Oysho Crop",
    category: "brassieres",
    price: 49.99,
    oldPrice: null,
    description: "Un sweat crop Oysho confortable et stylé, parfait pour un look sport-détente après l'entraînement.",
    image: "images/produits/sweat_oysho.jpg",
    badge: null,
    colors: ["#E63946", "#FF9F1C", "#4A90D9", "#1a1a2e"],
    sizes: ["Unique"],
    rating: 4.6,
    reviews: 234,
    featured: false
  },
  {
    id: 12,
    name: "Sweat Puma Essential",
    category: "brassieres",
    price: 59.99,
    oldPrice: null,
    description: "Le sweat indispensable de Puma, alliant douceur du coton et coupe classique.",
    image: "images/produits/sweat_puma.jpg",
    badge: null,
    colors: ["#E63946", "#4A90D9", "#F0E6D3"],
    sizes: ["Unique"],
    rating: 4.9,
    reviews: 389,
    featured: true
  },

  /* ---------- NOUVEAUTÉS ---------- */
  {
    id: 13,
    name: "Jacket Nike Sportswear",
    category: "brassieres",
    price: 99.99,
    oldPrice: null,
    description: "Veste Nike haute performance, conçue pour vous protéger avec style lors de vos activités extérieures.",
    image: "images/produits/jacket_nike.jpg",
    badge: null,
    colors: ["#8A9A5B", "#2D2D2D"],
    sizes: ["S", "M", "L"],
    rating: 4.8,
    reviews: 42,
    featured: false
  },
  {
    id: 14,
    name: "Jacket Adidas Originals",
    category: "brassieres",
    price: 109.99,
    oldPrice: null,
    description: "L'iconique veste Adidas Originals, le mélange parfait entre héritage sportif et look urbain.",
    image: "images/produits/jacket_adidas.jpg",
    badge: null,
    colors: ["#F5F0EC", "#2D2D2D", "#FFB3C1"],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.5,
    reviews: 112,
    featured: false
  },
  {
    id: 15,
    name: "Jacket Puma Windbreaker",
    category: "brassieres",
    price: 79.99,
    oldPrice: null,
    description: "Coupe-vent Puma léger et compact, idéal pour vos entraînements par temps venteux.",
    image: "images/produits/jacket_puma.jpg",
    badge: null,
    colors: ["#F5F0EC", "#E2DDD8"],
    sizes: ["36", "37", "38", "39", "40"],
    rating: 4.9,
    reviews: 320,
    stock: 3,
    featured: true
  },
  {
    id: 16,
    name: "Jacket Oysho Fitness",
    category: "brassieres",
    price: 89.99,
    oldPrice: null,
    description: "Veste technique Oysho offrant confort et liberté de mouvement pour vos séances de fitness.",
    image: "images/produits/jacket_oysho.jpg",
    badge: null,
    colors: ["#1a1a2e", "#FFB3C1"],
    sizes: ["Unique"],
    rating: 4.7,
    reviews: 85,
    featured: false
  },
  /* ---------- NOUVEAUX PRODUITS AJOUTÉS ---------- */
  {
    id: 17,
    name: "Jacket New Balance",
    category: "brassieres",
    price: 119.99,
    oldPrice: null,
    description: "Veste New Balance premium, alliant technologie textile avancée et design moderne.",
    image: "images/produits/jacket_nb.jpg",
    badge: null,
    colors: ["#F5F0EC", "#2D2D2D"],
    sizes: ["36", "37", "38", "39", "40", "41"],
    rating: 4.9,
    reviews: 124,
    featured: true
  },
  {
    id: 18,
    name: "New Balance 530",
    category: "chaussures",
    price: 119.99,
    oldPrice: null,
    description: "L'icône du style Dad-shoe. Confort exceptionnel grâce à la technologie ABZORB.",
    image: "images/produits/nb530.jpg",
    badge: "Collector",
    colors: ["#2D2D2D", "#FFFFFF"],
    sizes: ["36", "37", "38", "39", "40", "41"],
    rating: 4.7,
    reviews: 45,
    featured: false
  },
  {
    id: 19,
    name: "Nike Dunk Low",
    category: "chaussures",
    price: 109.99,
    oldPrice: null,
    description: "Le classique incontournable de Nike, alliant style rétro et confort moderne pour un look quotidien parfait.",
    image: "images/produits/dunk_low.jpg",
    badge: null,
    colors: ["#2D2D2D", "#4A90D9"],
    sizes: ["36", "37", "38", "39", "40", "41"],
    rating: 4.6,
    reviews: 88,
    featured: false
  },
  {
    id: 20,
    name: "Adidas Samba",
    category: "chaussures",
    price: 99.99,
    oldPrice: null,
    description: "Née sur les terrains de football, la Samba est devenue une icône du style urbain avec son design intemporel.",
    image: "images/produits/adidas_samba.jpg",
    badge: "Iconic",
    colors: ["#D4A5A5", "#2D2D2D"],
    sizes: ["36", "37", "38", "39", "40", "41"],
    rating: 4.8,
    reviews: 62,
    featured: true
  },
  {
    id: 21,
    name: "Nike Zoom Vomero 5",
    category: "chaussures",
    price: 149.99,
    oldPrice: null,
    description: "Une foulée fluide et un style technique complexe. La Vomero 5 offre un amorti exceptionnel pour vos journées actives.",
    image: "images/produits/vomero5.jpg",
    badge: "Premium",
    colors: ["#F5F0EC", "#A37B92"],
    sizes: ["36", "37", "38", "39", "40", "41"],
    rating: 4.5,
    reviews: 37,
    featured: false
  },
  {
    id: 22,
    name: "Robe Fitness",
    category: "brassieres",
    price: 49.99,
    oldPrice: null,
    description: "Une robe de fitness élégante et technique, offrant une totale liberté de mouvement avec un style moderne et épuré.",
    image: "images/produits/Robe_Fitness.jpg",
    badge: "Nouveau",
    colors: ["#2D2D2D", "#FFFFFF"],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.8,
    reviews: 15,
    featured: true
  },
  {
    id: 23,
    name: "ASICS GEL 1130",
    category: "chaussures",
    price: 129.99,
    oldPrice: null,
    description: "Inspirée des décennies de design ASICS, cette chaussure offre stabilité et confort grâce à la technologie GEL.",
    image: "images/produits/asics_gel.jpg",
    badge: null,
    colors: ["#1a1a2e", "#D4A5A5"],
    sizes: ["36", "37", "38", "39", "40", "41"],
    rating: 4.4,
    reviews: 53,
    featured: false
  },
  {
    id: 24,
    name: "Sac à dos Nike",
    category: "accessoires",
    price: 49.99,
    oldPrice: null,
    description: "Nombreuses poches de rangement et bretelles rembourrées pour un confort maximal lors de vos déplacements.",
    image: "images/produits/sac_nike.jpg",
    badge: null,
    colors: ["#2D2D2D"],
    sizes: ["Unique"],
    rating: 4.7,
    reviews: 94,
    featured: false
  },
  {
    id: 25,
    name: "Sac Puma",
    category: "accessoires",
    price: 39.99,
    oldPrice: null,
    description: "Large volume avec compartiment chaussures séparé. Robuste et stylé pour toutes vos aventures sportives.",
    image: "images/produits/sac_puma.jpg",
    badge: null,
    colors: ["#F5F0EC", "#8A9A5B"],
    sizes: ["Unique"],
    rating: 4.6,
    reviews: 41,
    featured: false
  },
  {
    id: 26,
    name: "Cabas H&M Sport",
    category: "accessoires",
    price: 19.99,
    oldPrice: null,
    description: "Un cabas léger et pratique pour transporter votre tenue de rechange après l'entraînement.",
    image: "images/produits/cabas_hm.jpg",
    badge: "Eco",
    colors: ["#2D2D2D"],
    sizes: ["Unique"],
    rating: 4.8,
    reviews: 112,
    featured: false
  },
  {
    id: 27,
    name: "Sac Oysho",
    category: "accessoires",
    price: 34.99,
    oldPrice: null,
    description: "Sac léger en toile résistante. Pratique pour transporter votre tapis de yoga et vos essentiels de studio.",
    image: "images/produits/sac_oysho.jpg",
    badge: "Pratique",
    colors: ["#FFFFFF", "#FFB3C1"],
    sizes: ["Unique"],
    rating: 4.7,
    reviews: 156,
    featured: true
  },
  {
    id: 28,
    name: "Casquette Adidas",
    category: "accessoires",
    price: 24.99,
    oldPrice: null,
    description: "Casquette réglable Adidas pour un style sportif et une protection optimale contre le soleil lors de vos sorties.",
    image: "images/produits/casquette_adidas.jpg",
    badge: null,
    colors: ["#2D2D2D", "#FFFFFF"],
    sizes: ["Unique"],
    rating: 4.9,
    reviews: 87,
    featured: false
  },
  {
    id: 29,
    name: "Chaussettes Nike",
    category: "accessoires",
    price: 14.99,
    oldPrice: null,
    description: "Pack de chaussettes de sport Nike Performance offrant amorti et maintien pour vos pieds durant l'effort.",
    image: "images/produits/chaussettes_nike.jpg",
    badge: null,
    colors: ["#FFFFFF", "#000000"],
    sizes: ["35-38", "39-42"],
    rating: 5.0,
    reviews: 342,
    featured: true
  },
  {
    id: 30,
    name: "Casque JBL",
    category: "accessoires",
    price: 79.99,
    oldPrice: null,
    description: "Vivez votre musique intensément avec le son JBL Pure Bass. Casque sans fil confortable idéal pour le sport.",
    image: "images/produits/casque_jbl.jpg",
    badge: "Tech",
    colors: ["#2D2D2D", "#1a1a2e"],
    sizes: ["Unique"],
    rating: 4.6,
    reviews: 74,
    featured: false
  },
  {
    id: 31,
    name: "Veste Adidas",
    category: "brassieres",
    price: 89.99,
    oldPrice: null,
    description: "Veste Adidas classique alliant style iconique et confort pour vos sessions de sport ou votre quotidien.",
    image: "images/produits/veste_adidas.jpg",
    badge: null,
    colors: ["#2D2D2D", "#8A9A5B"],
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.8,
    reviews: 189,
    featured: true
  },
  {
    id: 32,
    name: "Crop Top Puma",
    category: "brassieres",
    price: 27.99,
    oldPrice: null,
    description: "Un crop top Puma stylé et respirant, idéal pour vos séances de fitness ou un look décontracté.",
    image: "images/produits/croptop_puma.jpg",
    badge: null,
    colors: ["#2D2D2D", "#FFFFFF"],
    sizes: ["S", "M", "L"],
    rating: 4.5,
    reviews: 42,
    featured: false
  },
  {
    id: 33,
    name: "Sport Bra Oysho",
    category: "brassieres",
    price: 29.99,
    oldPrice: null,
    description: "Maintien modéré idéal pour le yoga et le pilates. Sans coutures pour éviter les frottements.",
    image: "images/produits/sportbra_oysho.jpg",
    badge: null,
    colors: ["#1a1a2e", "#D4A5A5"],
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.7,
    reviews: 131,
    featured: false
  },
  {
    id: 34,
    name: "Top Zippé Sport",
    category: "brassieres",
    price: 39.99,
    oldPrice: null,
    description: "Un top de sport zippé alliant technicité et style. Sa coupe ajustée et son tissu respirant garantissent un confort total lors de vos entraînements les plus intenses.",
    image: "images/produits/Top_Zippe_Sport.jpg",
    badge: "Nouveau",
    colors: ["#2D2D2D", "#FFFFFF", "#6B7A8D"],
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.7,
    reviews: 42,
    featured: true
  },
  {
    id: 35,
    name: "Combishort Sport",
    category: "leggings",
    price: 39.99,
    oldPrice: null,
    description: "Un combishort tout-en-un offrant un maintien optimal et une silhouette sculptée pour vos séances de yoga ou de fitness.",
    image: "images/produits/Combishort_sport.jpg",
    badge: "Nouveau",
    colors: ["#2D2D2D", "#A37B92"],
    sizes: ["S", "M", "L"],
    rating: 4.8,
    reviews: 12,
    featured: true
  },
  {
    id: 36,
    name: "Short Cycliste",
    category: "leggings",
    price: 24.99,
    oldPrice: null,
    description: "Le short cycliste indispensable pour bouger en toute liberté. Tissu anti-transpiration et coupe ajustée.",
    image: "images/produits/Short_cycliste.jpg",
    badge: null,
    colors: ["#2D2D2D", "#4A90D9", "#FF69B4"],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.6,
    reviews: 28,
    featured: false
  },
  {
    id: 37,
    name: "Short Cycliste Adidas",
    category: "leggings",
    price: 34.99,
    oldPrice: null,
    description: "Performance et style avec ce short cycliste Adidas. Idéal pour le cyclisme, le running ou un look sportswear tendance.",
    image: "images/produits/Short_cycliste_Adidas.jpg",
    badge: "Bestseller",
    colors: ["#2D2D2D", "#FFFFFF"],
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.9,
    reviews: 56,
    featured: true
  },
  {
    id: 38,
    name: "Sweat Zippé",
    category: "brassieres",
    price: 89.99,
    oldPrice: null,
    description: "Le sweat zippé Yoga allie style minimaliste et confort premium. Parfait pour vos sorties avant ou après l'entraînement.",
    image: "images/produits/Sweat_ zippe.jpg",
    badge: "Premium",
    colors: ["#FFFFFF", "#2D2D2D", "#A37B92"],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.8,
    reviews: 34,
    featured: false
  },
  {
    id: 39,
    name: "Hoodie Court",
    category: "brassieres",
    price: 44.99,
    oldPrice: null,
    description: "Un hoodie court moderne et confortable, idéal pour vos échauffements ou un look décontracté au quotidien.",
    image: "images/produits/Hoodie_court.jpg",
    badge: "Nouveau",
    colors: ["#2D2D2D", "#FFFFFF", "#D4A5A5"],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.7,
    reviews: 18,
    featured: true
  },
  {
    id: 40,
    name: "Pantalon Jogging",
    category: "leggings",
    price: 54.99,
    oldPrice: null,
    description: "Confortable et stylé, ce pantalon de jogging est idéal pour vos entraînements en extérieur ou pour rester à l'aise après le sport.",
    image: "images/produits/Pantalon_jogging.jpg",
    badge: null,
    colors: ["#2D2D2D", "#6B7A8D"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.7,
    reviews: 24,
    featured: false
  },
  {
    id: 41,
    name: "Shaker Gymshark",
    category: "accessoires",
    price: 14.99,
    oldPrice: null,
    description: "Le shaker Gymshark est l'accessoire indispensable pour vos séances de musculation. Pratique, hermétique et facile à nettoyer.",
    image: "images/produits/Shaker_Gymshark.jpg",
    badge: "Nouveau",
    colors: ["#2D2D2D", "#FFFFFF"],
    sizes: ["750ml"],
    rating: 4.8,
    reviews: 15,
    featured: false
  },
  {
    id: 42,
    name: "Sac de Sport",
    category: "accessoires",
    price: 49.99,
    oldPrice: null,
    description: "Un sac de sport spacieux et résistant, parfait pour transporter toutes vos affaires d'entraînement avec style et confort.",
    image: "images/produits/bag_sport.jpg",
    badge: "Nouveau",
    colors: ["#2D2D2D", "#A37B92", "#4A90D9"],
    sizes: ["Unique"],
    rating: 4.7,
    reviews: 20,
    featured: false
  },
  {
    id: 43,
    name: "Visière Nike",
    category: "accessoires",
    price: 19.99,
    oldPrice: null,
    description: "La visière Nike classique pour vous protéger du soleil avec style pendant vos entraînements en extérieur ou vos activités sportives.",
    image: "images/produits/Visiere_Nike.jfif",
    badge: null,
    colors: ["#2D2D2D", "#FFFFFF", "#FF69B4"],
    sizes: ["Unique"],
    rating: 4.5,
    reviews: 30,
    featured: false
  },
  {
    id: 44,
    name: "Top Performance Manches Longues",
    category: "brassieres",
    price: 49.99,
    oldPrice: null,
    description: "Un top de performance à manches longues, idéal pour les entraînements par temps frais. Tissu respirant et coupe ajustée pour un confort optimal.",
    image: "images/produits/Top_Performance_Manches_Longues.jpg",
    badge: "Nouveau",
    colors: ["#2D2D2D", "#FFFFFF", "#A37B92"],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.7,
    reviews: 22,
    featured: true
  },
  {
    id: 45,
    name: "Shaker Sport",
    category: "accessoires",
    price: 15.99,
    oldPrice: null,
    description: "Un shaker pratique et robuste, indispensable pour vos séances. Sa fermeture hermétique garantit un transport sans fuites.",
    image: "images/produits/Shaker_sport.jpg",
    badge: "Nouveau",
    colors: ["#2D2D2D", "#FFFFFF"],
    sizes: ["600ml"],
    rating: 4.7,
    reviews: 12,
    featured: false
  },
  {
    id: 46,
    name: "Corde à Sauter Fitness",
    category: "accessoires",
    price: 19.99,
    oldPrice: null,
    description: "Corde à sauter réglable et légère, idéale pour le cardio, l'échauffement ou l'amélioration de votre coordination. Poignées ergonomiques anti-dérapantes.",
    image: "images/produits/Corde_a_sauter_fitness.jpg",
    badge: "Nouveau",
    colors: ["#2D2D2D", "#FF69B4", "#4A90D9"],
    sizes: ["Unique"],
    rating: 4.6,
    reviews: 25,
    featured: false
  },
  {
    id: 47,
    name: "Sac à dos",
    category: "accessoires",
    price: 39.99,
    oldPrice: null,
    description: "Un sac à dos polyvalent et stylé, parfait pour transporter vos essentiels de sport ou pour une utilisation quotidienne.",
    image: "images/produits/Sac_a_dos.jpg",
    badge: "Nouveau",
    colors: ["#2D2D2D", "#A37B92", "#4A90D9"],
    sizes: ["Unique"],
    rating: 4.7,
    reviews: 18,
    featured: false
  },
  {
    id: 48,
    name: "Pantalon Jogging Large",
    category: "leggings",
    price: 59.99,
    oldPrice: null,
    description: "Un pantalon de jogging à coupe large offrant un confort absolu et un look décontracté très tendance. Parfait pour vos moments de détente ou vos entraînements légers.",
    image: "images/produits/Pantalon_jogging_large.jpg",
    badge: "Nouveau",
    colors: ["#2D2D2D", "#6B7A8D", "#F5F0EC"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.8,
    reviews: 14,
    featured: true
  },
  {
    id: 49,
    name: "Gants de Sport",
    category: "accessoires",
    price: 19.99,
    oldPrice: null,
    description: "Gants de sport offrant une protection optimale et une meilleure adhérence pour vos séances de musculation ou de fitness.",
    image: "images/produits/Gants_de_sport.jpg",
    badge: "Nouveau",
    colors: ["#2D2D2D", "#FF69B4"],
    sizes: ["S", "M", "L"],
    rating: 4.7,
    reviews: 10,
    featured: false
  },
  {
    id: 50,
    name: "Tapis de Yoga",
    category: "accessoires",
    price: 29.99,
    oldPrice: null,
    description: "Un tapis de yoga antidérapant et confortable pour toutes vos postures. Épaisseur optimale pour protéger vos articulations pendant l'exercice.",
    image: "images/produits/Tapis_de_yoga.jpg",
    badge: "Nouveau",
    colors: ["#A37B92", "#8A9A5B", "#2D2D2D"],
    sizes: ["Unique"],
    rating: 4.8,
    reviews: 15,
    featured: true
  },
  {
    id: 51,
    name: "Combinaison Fitness",
    category: "leggings",
    price: 54.99,
    oldPrice: null,
    description: "Une combinaison de fitness intégrale offrant un maintien compressif et une silhouette parfaitement galbée pour vos entraînements les plus intenses.",
    image: "images/produits/Combinaison_Fitness.jpg",
    badge: "Nouveau",
    colors: ["#2D2D2D", "#1a1a2e"],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.9,
    reviews: 8,
    featured: true
  },
  {
    id: 52,
    name: "T-shirt Fitness",
    category: "brassieres",
    price: 29.99,
    oldPrice: null,
    description: "Un t-shirt de fitness léger et respirant, parfait pour vos entraînements intenses ou un look sportif décontracté.",
    image: "images/produits/Tshirt_Fitness.jpg",
    badge: "Nouveau",
    colors: ["#2D2D2D", "#FFFFFF", "#6B7A8D"],
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.6,
    reviews: 20,
    featured: false
  }
];

/* =============================================
   UTILISATEURS STATIQUES
   ============================================= */
const STATIC_USERS = [
  {
    prenom: "Admin",
    nom: "FemSport",
    email: "admin@femsport.com",
    password: "Admin123!",
    phone: "0555000001"
  },
  {
    prenom: "Amina",
    nom: "Ummto",
    email: "test@femsport.com",
    password: "Test123!",
    phone: "0661234567"
  },
  {
    prenom: "Sara",
    nom: "Ummto",
    email: "sara@sport.com",
    password: "Sara456@",
    phone: "0770987654"
  }
];

/* =============================================
   CATÉGORIES
   ============================================= */
const CATEGORIES = [
  {
    id: "leggings",
    label: "Leggings",
    icon: "",
    description: "Taille haute, 7/8, compression...",
    color: "#FF4800", // Bright Crimson
    count: PRODUCTS.filter(p => p.category === "leggings").length
  },
  {
    id: "brassieres",
    label: "Brassières & Tops",
    icon: "",
    description: "Maintien fort, modéré, yoga...",
    color: "#FF0055", // Vibrant Pink
    count: PRODUCTS.filter(p => p.category === "brassieres").length
  },
  {
    id: "chaussures",
    label: "Chaussures",
    icon: "",
    description: "Running, training, athleisure...",
    color: "#00E5FF", // Cyan Electric
    count: PRODUCTS.filter(p => p.category === "chaussures").length
  },
  {
    id: "accessoires",
    label: "Accessoires",
    icon: "",
    description: "Gourdes, bandeaux, tapis...",
    color: "#9DFF00", // Volt Green (Nike Style)
    count: PRODUCTS.filter(p => p.category === "accessoires").length
  }
];
